version: '3.9'

services:
  client:
    build: ./client
    ports:
      - "80:80"
    environment:
      - BACKEND_URL=http://node_service:3001
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - './client:/app'
    stdin_open: true
    tty: true
    networks:
      - mynetwork
    depends_on:
      - node_service

  node_service:
    build: ./node_service
    ports:
      - "3001:3001"
    volumes:
      - ./node_service:/app
    environment:
      - NODE_ENV=development
      - PYTHON_BASE_URL=http://python_service:9000
    networks:
      - mynetwork
    depends_on:
      - python_service

  python_service:
    build: ./python-service
    ports:
      - "9000:9000"
    volumes:
      - ./python-service:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://postgres:1234567@postgres:5432/fastapi_db
    networks:
      - mynetwork
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
      POSTGRES_DB: fastapi_db
    ports:
      - "5433:5432" # Changed host port to 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
volumes:
  postgres_data:
